name: Checking Model

on:
  release:
    types: [released]

# TODO: add tags
env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.ref_name }}

jobs:
  torchhub:
    name: Load Model with Torch Hub
    runs-on: ubuntu-latest
    container:
      image: ruhyadi/sample-actions:v1.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Load Model
        run: python3 hubconf.py

  delete-release:
    needs: [torchhub]
    name: Delete Release
    runs-on: ubuntu-latest
    if: always() && (needs.torchhub.result == 'failure')
    steps:
      - name: Delete Tag and Release 
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: ${{ github.ref_name }}
          repo: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}