name: Checking Model

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  checking-torch-hub:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install Depedencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==1.8.1 torchvision==0.9.1
      - name: Check Torch Hub 
        run: |
          python hubconf.py